CREATE TABLE IF NOT EXISTS T_FIN_TRANSFER (
                                              FIN_TRANSFER_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    FIN_TRANSFER_ACCOUNTORIGIN VARCHAR(10) NOT NULL,
    FIN_TRANSFER_ACCOUNTDESTINATION VARCHAR(10) NOT NULL,
    FIN_TRANSFER_VALUE DECIMAL(15, 2) NOT NULL,
    FIN_TRANSFER_FEE DECIMAL(15, 2) NOT NULL,
    FIN_TRANSFER_TOTALVALUE DECIMAL(15, 2) NOT NULL,
    FIN_TRANSFER_TRANSFERDATE TIMESTAMP NOT NULL,
    FIN_TRANSFER_DTCREATED TIMESTAMP NOT NULL,
    FIN_TRANSFER_DTCANCELED TIMESTAMP NULL
    );